### ISSUE TITLE
Data field is missing for Secrets

### ISSUE THREAD

**Issue by PrasadG193** [PrasadG193/kyaml2go#20]
Data field is missing while generating code for K8s Secrets
```
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm
```
