### ISSUE TITLE
CPU resources are recommended resource.NewMilliQuantity

### ISSUE THREAD

**Issue by ysicing** [PrasadG193/kyaml2go#26]
```yaml
resources:
  limits:
    cpu: 500m
    memory: 200Mi
  requests:
     cpu: 100m
     memory: 10Mi
```

```go
Limits: corev1.ResourceList{
  "cpu":    *resource.NewQuantity(500, resource.DecimalSI),
  "memory": *resource.NewQuantity(209715200, resource.BinarySI),
},
Requests: corev1.ResourceList{
  "cpu":    *resource.NewQuantity(100, resource.DecimalSI),
  "memory": *resource.NewQuantity(10485760, resource.BinarySI),
},
```

As mentioned, CPU resources default to 500 cores ,not 0.5 core?
