### ISSUE TITLE
Support for generating go code for CR created with Dynamic client go 

### ISSUE THREAD

**Issue by linuxbsdfreak** [PrasadG193/kyaml2go#41]
Hi,

I would like to generate go code based on dynamic client-go for unstructured data without CRDs

https://github.com/kubernetes/client-go/blob/master/examples/dynamic-create-update-delete-deployment/main.go

Sample example for converting the below yaml to to go code

```
apiVersion: aws.platformref.delphi.sap.io/v1alpha1
kind: PostgreSQLInstance
metadata:
  name: complex-composite-db-public-xxx
  namespace: default
spec:
  id: ""
  parameters:
    dbinstance:
       storageGB: 5
       dbInstanceClass: db.t2.small
       multiAZ: true
       engineVersion: "9.6"
       storageType: "gp2"
       region: eu-central-1
       vpcId: vpc-xxxx
       subnetIds:
         - subnet-xxx
         - subnet-xxx
       publiclyAccessible: true
       whiteListIPRanges:
         - "0.0.0.0/0"
    dbconfig:
       dbName: test
       dbSecretNamespace: default
  compositionSelector:
    matchLabels:
      provider: aws
      vpc: gardener
  writeConnectionSecretToRef:
    name: test
```
